version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: date
          command: date "+%Y-%m-%dT%H:%M:%S%z"
      - deploy:
          name: deploy
          command: echo deploy


workflows:
  version: 2
  daily:
    triggers:
      - schedule:
         cron: "20 1 * * *"
         filters:
           branches:
             only:
               - wip-test
    jobs:
      - build
